user: # 在填了cookies的情况下优先使用cookies上传，如需使用用户名密码上传请注释掉cookies
    cookies:
        SESSDATA: your SESSDATA
        bili_jct: your bili_jct
        DedeUserID: your DedeUserID
    account:
        username: your usrname
        password: your password
# 默认通过网页接口上传,可选通过操作chrome上传,此时需要填写chromedriver路径
#chromedriver_path: /usr/local/bin/chromedriver

# b站上传线路选择，默认为自动模式，目前可手动切换为bda2, kodo, ws, qn。
lines: AUTO
# 单文件并发上传数，未达到带宽上限时增大此值可提高上传速度
threads: 3
# 录像单文件大小限制，单位Byte，超过此大小分段下载
file_size: 2621440000

streamers:
    星际2INnoVation吕布卫星人族天梯第一视角:
        url:
            - https://www.twitch.tv/innovation_s2
            - https://www.panda.tv/1160340
        tid: 171
        cover_path: /cover/up.jpg
        tags:
          - 星际争霸2
          - 电子竞技
    星际2soO输本虫族天梯第一视角:
        url:
            - https://www.twitch.tv/sc2soo
            - https://www.panda.tv/1150595
    星际2sOs狗哥神族天梯第一视角:
        url:
            - https://www.panda.tv/1160930
            - https://www.twitch.tv/jinairsos1
    星际2Stats拔本神族天梯第一视角:
        url:
            - https://www.twitch.tv/kimdaeyeob3
    星际2Dark暗本虫族天梯第一视角:
        url:
            - https://www.twitch.tv/qkrfuddn0
    星际2Scarlett噶姐虫族天梯第一视角:
        url:
            - https://www.twitch.tv/scarlettm
    星际2GuMiho砸本人族天梯第一视角:
        url:
            - https://www.twitch.tv/gumiho
    星际2Maru人族天梯第一视角:
        url:
            - https://www.twitch.tv/maru072
    星际2TY全教主全太阳人族天梯第一视角:
        url:
            - https://www.twitch.tv/sc2tyty
    星际2ByuN武圣人族天梯第一视角:
        url:
            - https://www.twitch.tv/byunprime
    星际2小herO神族天梯第一视角:
        url:
            - https://www.twitch.tv/dmadkr0818
    星际2Zest神族天梯第一视角:
        url:
            - https://www.twitch.tv/sc2_zest
    星际2PartinG跳跳胖丁神族天梯第一视角:
        url:
            - https://www.twitch.tv/partingthebigboy
    星际2Rogue脑虫虫族天梯第一视角:
        url:
            - https://www.twitch.tv/roguejinair
    星际2Classic经典神皇神族第一视角:
        url:
            - https://www.twitch.tv/kimclassic
